version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: adaptive_learning_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: adaptive_learning
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Adminer (Lightweight DB Admin Tool)
  adminer:
    image: adminer:latest
    container_name: adaptive_learning_adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app_network
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge